version: '3.8'

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - shared-net
    volumes:
      - /var/lib/postgresql/data

  app:
    image: library
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - localstack
      - redis
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/library?autocommit=true
      - SERVER_PORT=8082
      - spring.redis.host=redis
      - spring.redis.port=6379
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.jpa.hibernate.ddl-auto = update
      - cloud.aws.secrets-manager.end-point.uri=http://localstack:4566
    restart: "no"
    networks:
      - shared-net


  localstack:
    image: localstack/localstack:latest
    hostname: localstack
    environment:
      - SERVICES=s3,secretsmanager
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-3
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge
